#https://artifacthub.io/packages/helm/vmware-tanzu/velero
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.5.0
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: inject-metadata-velero-plugin
    image: ghcr.io/cloudbees-oss/inject-metadata-velero-plugin:main
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  provider: aws
  backupStorageLocation:
    bucket: ${bucket_name}
  volumeSnapshotLocation:
    config:
      region: ${velero_region}
serviceAccount:
  server:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: ${rol_arn}
    name: ${service_account_name}
credentials:
  useSecret: false
nodeSelector:
  kubernetes.io/os: linux
  kubernetes.io/arch: amd64
