apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-prometheus-stack-ray-monitor
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - ${namespace}
  selector:
    #oc
    matchLabels:
      app.kubernetes.io/name : cloudbees-core
    #controllers
    matchExpressions:
      - key: "com.cloudbees.cje.type"
        operator: "Exists"
  endpoints:
    - port: http
      interval: "30s"
      relabelings:
        - action       : "replace"
          replacement  : "/$${1}/prometheus/"
          sourceLabels : ["__meta_kubernetes_endpoints_name"]
          targetLabel  : "__metrics_path__"
